[supabase]
SUPABASE_URL="https://qcrseofanlopbfsghwoj.supabase.co"
SUPABASE_ANON_KEY="sb_publishable_jxx6kAGvEMm07FzARm2j5A_Aa7Oz5kT"

[backend]
url="https://ai-resume-ats-tq51.onrender.com"

[google_oauth]
redirect_uri="http://localhost:8501"